name: Build, Test, Check & generate APK

on:
  push:
    branches:
      - main
  

jobs:
  verify_code_quality:
    name: Verify Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify Code Quality
        run: ./gradlew detekt ktlintCheck



  build_test_check:
    name: Build,Test & Check
    needs: verify_code_quality
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp ci-cd/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run local tests with coverage
        run: ./gradlew testDebugUnitTest

      - name: Check lint
        run: ./gradlew :app:lintRelease

      - name: Build with gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Playground.apk
          path: app/build/outputs/apk/debug/app-debug.apk