name: verify screenshots

on:
  push

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # Download screenshots from main branch
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: screenshots
          path: '**/core/ui/src/test/screenshots'
          workflow: StoreScreenShots.yml
          branch: main

      - name: verify test
        id: verify-test
        run: |
          # If there is a difference between the screenshots, the test will fail.
          ./gradlew verifyRoborazziDebug --stacktrace

      - uses: actions/upload-artifact@v4.3.3
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v4.3.3
        if: ${{ always() }}
        with:
          name: screenshot-diff-reports
          path: |
            **app/build/reports
          retention-days: 30

      - uses: actions/upload-artifact@v4.3.3
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: |
            **/build/test-results
          retention-days: 30
